### ISSUE TITLE
221.* Support

### ISSUE THREAD

**Issue by lilithium-hydride** [Jmorjsm/rose-pine-intellij#3]
Currently, the plugin only supports up to version 213. 221 is in EAP now, and the theme is marked as incompatible.

**Comment by jonmorgs** [comment]
@lilithium-hydride Thank you for reporting this. I've looked at the compatibility check for 221 and it looks like it will be compatible. Unfortunately I cannot update the compatibility range, but hopefully this will be done automatically?
![image](https://user-images.githubusercontent.com/6062228/152563161-627e106e-0c6c-4a7e-a821-23f68d238a82.png)

**Comment by lilithium-hydride** [comment]
Ah alright, one of my themes is compatible so I assumed it was something controlled by maintainers. It did just release though, so it's possible that things are still shifting around in their systems.

**Comment by jonmorgs** [comment]
@lilithium-hydride Turns out this was something I needed to change! I bumped the compatibility range in version 0.0.4.
![image](https://user-images.githubusercontent.com/6062228/152785545-008af911-b45a-4aa2-bf93-5dc272e6e913.png)
![image](https://user-images.githubusercontent.com/6062228/152785557-86337e8e-3cb5-4a6c-9e63-541f5e6073e8.png)
